- .gitignore
Make this project friendly for idea.
> Add *.iml to .gitignore

- content/index.html
- content/index.xml
- content/mailing_lists.html
- src/mailing_lists.md
Replace spark.apache.org with kyuubi.apache.org: https://kyuubi.apache.org/mailing_lists.html
> Fix mailing lists

- content/docs/latest
- content/docs/stable
Update the following links:
- https://kyuubi.apache.org/docs/latest/
- https://kyuubi.apache.org/docs/stable/
> Update latest and stable to r1.3.1-incubating

- config.toml
- layouts/index.html
- layouts/partials/header.html
https://whimsy.apache.org/pods/project/kyuubi we shall pass all the checks here
> Fix ASF Events

- .gitignore
- .gitmodules
- src/mailing_lists.md
> Update mailing lists page

- src/new_committer_process.md
Add a new page `New Committer Process` in community
> New Committer Process

- src/pull_request.md
I am unable to build the site though:
```
$ hugo version
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2021-02-09T18:47:48Z (ubuntu 0.80.0-6)
$ hugo
Total in 1 ms
Error: add site dependencies: create deps: 1 error(s) decoding:
* 'Goldmark.Parser.Attribute' expected type 'bool', got unconvertible type 'map[string]interface {}'
```
> Improve "Pull Request" page by explaining the usage of GitHub Actions and TravisCI

- layouts/custompage/news_table.html
- src/news/2021-12-25-new-committers.md
- src/news/2022-03-27-new-committers.md
- static/css/kyuubi.css
> Add ann committers to news

- src/become_committer.md
> Add current committers

- config.toml
try to fix https://github.com/apache/incubator-kyuubi/issues/2315 issue 2
> [feat] add keep quotes config in config.toml

- src/en/become_pmc_member.md
- src/en/new_pmc_member_process.md
- src/zh/become_pmc_member.md
- src/zh/new_pmc_member_process.md
Add:
- New PMC Process
- Become PMC
> New pmc docs

- src/en/become_pmc_member.md
this pr including fixes in src/en/become_pmc_member.md as following:
- PMC -> PPMC or Podling PMC
- PPMC member requirements updating
> Update Become a PPMC page

- config.toml
> Add docker repo link

- src/en/become_committer.md
- src/zh/become_committer.md
- add `Bowen Liang` (bowenliang)  as new committer
> Add committer

- src/en/become_pmc_member.md
- src/zh/become_pmc_member.md
Add `Fu Chen` as a new PMC member
> Add new PMC member

- static/css/kyuubi.css
> Extend margin-top of .footer class to 30px

- src/en/developer-tools.md
- src/zh/developer-tools.md
Fix typo in developer-tools.md
> Fix typo in developer-tools.md

- src/en/become_committer.md
- src/en/news/2023-04-07-new-committers.md
- src/zh/become_committer.md
- src/zh/news/2023-04-07-new-committers.md
add Yaodong Zhang (zhangyaodong) as new committer
> Add Yaodong Zhang in committer list

- src/en/become_committer.md
- src/zh/become_committer.md
> Add Paul Lin as committer

- src/en/become_committer.md
- src/en/news/2023-10-11-new-committers.md
- src/zh/become_committer.md
- src/zh/news/2023-10-11-new-committers.md
> Add Binjie Yang as committer

- layouts/index.html
- layouts/partials/navbar.html
https://kyuubi.readthedocs.io/en/v1.8.1-docs/
> Fix v1.8.1 docs

- src/en/become_committer.md
- src/en/news/2023-04-08-new-committers.md
- src/zh/become_committer.md
- src/zh/news/2023-04-08-new-committers.md
The PR changes Organization for Denis Krivenko and fixes minor typo.
> Update Organization for Denis Krivenko
